version: '3.8'

services:
  parking-service:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: parking-service
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 